# Generated by Django 2.1.7 on 2019-02-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20190210_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectspage',
            name='description_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectspage',
            name='description_nl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
