# Generated by Django 2.1.7 on 2019-02-16 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20190216_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectspage',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='projectspage',
            name='description_nl',
        ),
    ]
