# Generated by Django 2.1.7 on 2019-02-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20190216_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technologyused',
            options={'verbose_name': 'Technology', 'verbose_name_plural': 'Technologies'},
        ),
    ]
