# Generated by Django 2.1.7 on 2019-02-18 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('projects', '0012_auto_20190218_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter1', models.CharField(blank=True, help_text='This should be the same as the Technology snippet you add', max_length=255, null=True)),
                ('filter2', models.CharField(blank=True, help_text='This should be the same as the Technology snippet you add', max_length=255, null=True)),
                ('filter3', models.CharField(blank=True, help_text='This should be the same as the Technology snippet you add', max_length=255, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
