# Generated by Django 2.1.7 on 2019-02-16 08:56

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190210_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro_left_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_left_nl',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
