# Generated by Django 2.1.7 on 2019-02-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190216_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='intro_heading_en',
            new_name='portfolio_heading',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='intro_heading_nl',
            new_name='portfolio_sub_heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_left_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_left_nl',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_right_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_right_nl',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_sub_heading_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_sub_heading_nl',
        ),
    ]
