# Generated by Django 2.1.7 on 2019-02-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190218_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliosettings',
            name='email',
            field=models.CharField(blank=True, help_text='Your email', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='heading',
            field=models.CharField(blank=True, help_text='Your title', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='name',
            field=models.CharField(blank=True, help_text='Your name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='social_github',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='social_linkedin',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='social_twitter',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='stat_description_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='stat_description_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='stat_description_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='stat_description_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='stat_number_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='stat_number_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='stat_number_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='stat_number_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='telephone',
            field=models.CharField(blank=True, help_text='Your telephone', max_length=255, null=True),
        ),
    ]
