# Generated by Django 2.1.7 on 2019-02-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_googleanalytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleanalytics',
            name='analytics_code',
            field=models.TextField(blank=True, help_text='Your analytics tracking code', null=True),
        ),
    ]
